idf_component_register(
    SRCS
        "src/stepper_driver.cpp"
        "src/homing_controller.cpp"
        "src/motion_controller.cpp"
        "src/config_manager.cpp"
        "src/console_commands.cpp"
    INCLUDE_DIRS
        "include"
    PRIV_INCLUDE_DIRS
        "src"
    REQUIRES
        driver
        esp_timer
        freertos
        esp_system
        esp_hw_support
        tmcstepper
        nvs_flash
        kd_common
        console
)
